<?php
/**
 * PO Importer — imports string translations from PO files.
 *
 * Uses WordPress core POMO library. Compatible with files generated by
 * Polylang Pro and by this HD module.
 *
 * @package HD\Modules\PLL\ImportExport
 */

namespace HD\Modules\PLL\ImportExport\Format;

use HD\Modules\PLL\ImportExport\Contracts\ImporterInterface;
use HD\Modules\PLL\ImportExport\FileFormatFactory;

defined( 'ABSPATH' ) || exit;

final class PoImporter implements ImporterInterface {

	private \PO $po;
	private bool $yielded = false;
	private int $cursor   = 0;

	public function __construct() {
		require_once ABSPATH . '/wp-includes/pomo/po.php';
		$this->po = new \PO();
	}

	public function importFromFile( string $filepath ): bool|\WP_Error {
		if ( ! $this->po->import_from_file( $filepath ) ) {
			return new \WP_Error( 'pll_po_invalid', __( 'Error: Invalid PO file.', 'hd' ) );
		}

		return true;
	}

	public function getTargetLanguage(): string|false {
		// Official header (PLL >= 3.3.1).
		if ( ! empty( $this->po->headers['Language'] ) ) {
			return $this->po->headers['Language'];
		}

		// Backward compat (PLL < 3.3.1).
		if ( ! empty( $this->po->headers['Language-Target'] ) ) {
			return $this->po->headers['Language-Target'];
		}

		return false;
	}

	public function getSiteReference(): string|false {
		return $this->po->headers['X-Polylang-Site-Reference']
			?? $this->po->headers['Site-Reference']
			?? false;
	}

	public function getGeneratorName(): string {
		$header = $this->po->headers['Project-Id-Version'] ?? '';

		if ( ! is_string( $header ) || '' === $header ) {
			return '';
		}

		$parts = explode( '/', trim( $header, '/ ' ) );
		array_pop( $parts ); // Remove version.
		$name = trim( implode( '/', $parts ) );

		// Backward compat with PLL < 3.3.
		return 'POLYLANG_EXPORT' === $name ? FileFormatFactory::APP_NAME : $name;
	}

	/**
	 * PO files yield all string translations as a single batch entry.
	 * The PO object itself contains all Translation_Entry objects.
	 */
	public function getNextEntry(): array {
		if ( $this->yielded ) {
			return [];
		}

		$this->yielded = true;

		return [
			'type' => 'strings-translations',
			'id'   => null,
			'data' => $this->po,
		];
	}
}
