<?php

use SPL\Core\Helper;

defined( 'ABSPATH' ) || exit;

add_action(
	'acf/include_fields',
	static function (): void {
		if ( ! function_exists( 'acf_add_local_field_group' ) ) {
			return;
		}

		$roles    = [ 'administrator', 'editor', 'author' ];
		$location = array_map(
			static fn( $role ) => [
				[
					'param'    => 'user_role',
					'operator' => '==',
					'value'    => Helper::toString( $role ),
				],
			],
			$roles
		);

		acf_add_local_field_group(
			[
				'key'                   => 'group_67dbdc6a82d99',
				'title'                 => __( 'Author Box', 'SPL' ),
				'fields'                => [
					[
						'key'               => 'field_67dbdc6b3d3de',
						'label'             => __( 'Alternative Name', 'SPL' ),
						'name'              => 'author_alt_name',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					],
					[
						'key'               => 'field_67dbdc6b3d4df',
						'label'             => __( 'Alternative Job', 'SPL' ),
						'name'              => 'author_alt_job',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					],
					[
						'key'               => 'field_68f0bda1d4155',
						'label'             => __( 'Alternative Slogan', 'SPL' ),
						'name'              => 'author_alt_slogan',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 3,
						'placeholder'       => '',
						'new_lines'         => 'br',
					],
					[
						'key'               => 'field_67dbde8acc4c4',
						'label'             => __( 'Alternative Profile Picture', 'SPL' ),
						'name'              => 'author_alt_profile_picture',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'return_format'     => 'id',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'small-150',
					],
					[
						'key'               => 'field_68064a1bc7e01',
						'label'             => __( 'Alternative Short Description', 'SPL' ),
						'name'              => 'author_alt_short_description',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => 'Brief summary displayed in author cards and listings.',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'default_value'     => '',
						'allow_in_bindings' => 0,
						'tabs'              => 'all',
						'toolbar'           => 'basic',
						'media_upload'      => 0,
						'delay'             => 0,
					],
					[
						'key'               => 'field_67dbdf4ecc4c5',
						'label'             => __( 'Alternative Biographical Info', 'SPL' ),
						'name'              => 'author_alt_biographical_info',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => 'Full biography content displayed on the author detail page.',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'default_value'     => '',
						'allow_in_bindings' => 0,
						'tabs'              => 'all',
						'toolbar'           => 'full',
						'media_upload'      => 1,
						'delay'             => 0,
					],
					[
						'key'               => 'field_68f0a0296e2b3',
						'label'             => __( 'Alternative Social Info', 'SPL' ),
						'name'              => 'author_alt_social_info',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => 'Add Row',
						'rows_per_page'     => 20,
						'sub_fields'        => [
							[
								'key'               => 'field_68f0a0526e2b4',
								'label'             => __( 'Name', 'SPL' ),
								'name'              => 'social_name',
								'aria-label'        => '',
								'type'              => 'select',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '20',
									'class' => '',
									'id'    => '',
								],
								'choices'           => [
									'facebook'  => 'Facebook',
									'x'         => 'X (twitter)',
									'linkedin'  => 'Linkedin',
									'tiktok'    => 'Tiktok',
									'messenger' => 'Messenger',
									'telegram'  => 'Telegram',
									'youtube'   => 'Youtube',
									'instagram' => 'Instagram',
									'zalo'      => 'Zalo',
									'envelope'  => 'Email',
									'phone'     => 'Hotline',
									'github'    => 'Github',
								],
								'default_value'     => false,
								'return_format'     => 'value',
								'multiple'          => 0,
								'allow_null'        => 0,
								'allow_in_bindings' => 0,
								'ui'                => 0,
								'ajax'              => 0,
								'placeholder'       => '',
								'create_options'    => 0,
								'save_options'      => 0,
								'parent_repeater'   => 'field_68f0a0296e2b3',
							],
							[
								'key'               => 'field_68f0a06c6e2b5',
								'label'             => __( 'URL', 'SPL' ),
								'name'              => 'social_url',
								'aria-label'        => '',
								'type'              => 'link',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '80',
									'class' => '',
									'id'    => '',
								],
								'return_format'     => 'array',
								'allow_in_bindings' => 0,
								'parent_repeater'   => 'field_68f0a0296e2b3',
							],
						],
					],
				],
				'location'              => $location,
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			]
		);
	}
);
