<?php
/**
 * HD Child Theme - Functions
 *
 * Lightweight child theme that loads inline CSS/JS for quick fixes.
 * No build process required.
 *
 * @package HD-Child
 * @author  HD
 */

defined( 'ABSPATH' ) || exit;

/**
 * Enqueue inline assets (directly loadable, no build required).
 *
 * These files are for emergency patches and quick fixes.
 * Located at theme root: inline.css, inline.js
 *
 * Parent theme handle names (generated by Asset class):
 * - CSS: 'main-css' (from main.scss via pattern: {slug}-{ext})
 * - JS: 'index-js' (from index.js via pattern: {slug}-{ext})
 *
 * @return void
 */
function hd_child_enqueue_assets(): void {
	$themeDir = get_stylesheet_directory();
	$themeUri = get_stylesheet_directory_uri();

	$cssFile = $themeDir . '/inline.css';
	$jsFile  = $themeDir . '/inline.js';

	// Minimum file size to be considered meaningful content.
	$minSize = 300;

	// Parent theme handles (hardcoded - pattern: {slug}-{extension}).
	$parentCssHandle = 'tailwind-css';
	$parentJsHandle  = 'index-js';

	// Enqueue inline.css if it exists and has meaningful content.
	if ( is_file( $cssFile ) && filesize( $cssFile ) > $minSize ) {
		$css_deps = wp_style_is( $parentCssHandle, 'registered' ) ? [ $parentCssHandle ] : [];
		wp_enqueue_style(
			'hd-child-inline',
			$themeUri . '/inline.css',
			$css_deps,
			filemtime( $cssFile )
		);
	}

	// Enqueue inline.js if it exists and has meaningful content.
	if ( is_file( $jsFile ) && filesize( $jsFile ) > $minSize ) {
		$js_deps = wp_script_is( $parentJsHandle, 'registered' ) ? [ $parentJsHandle ] : [];
		wp_enqueue_script(
			'hd-child-inline',
			$themeUri . '/inline.js',
			$js_deps,
			filemtime( $jsFile ),
			true // In footer.
		);
	}
}

add_action( 'wp_enqueue_scripts', 'hd_child_enqueue_assets', 100 );
