<?php
return ['x-generator'=>'GlotPress/4.0.3','translation-revision-date'=>'2026-04-09 11:52:32+0000','plural-forms'=>'nplurals=2; plural=n > 1;','project-id-version'=>'Plugins - Multilingual Contact Form 7 with Polylang - Stable (latest release)','language'=>'fr','messages'=>['Settings'=>'Réglages','Example Plugin Settings'=>'Exemple de réglage de l’extension','Remove file'=>'Retirer le fichier','Upload File'=>'Téléverser un fichier','Use file'=>'Utiliser un fichier','Upload file'=>'Téléverser un fichier','In some installations, form messages received after sending data are not being translated. Activate this feature if you have this issue. This may however cause another issue that directly after a language switch the translation may still be in the old language.'=>'Dans certaines installations, les messages de formulaire reçus après l’envoi de données ne sont pas traduits. Activez cette fonctionnalité si vous rencontrez ce problème. Cela peut toutefois entraîner un autre problème : juste après un changement de langue, la traduction peut toujours être effectuée dans l’ancienne langue.','Form messages fix'=>'Correction des messages des formulaires','Experimental features'=>'Fonctionnalités expérimentales','Multilangual CF7 Polylang'=>'Multilangual CF7 Polylang','Warning! There are untranslatable custom strings for the messages in this form. <br>
                                See the %s panel below for more information.'=>'Attention ! Ce formulaire contient des chaînes personnalisées intraduisibles. <br>
Veuillez consulter l’encadré %s ci-dessous pour plus d’informations.','Reset Message Strings'=>'Réinitialiser les chaînes de message','Reset custom message translations'=>'Réinitialiser les traductions des messages personnalisés','Multilangual CF7 with Polylang'=>'Multilangual CF7 with Polylang','Confirm if you want to reset the message strings'=>'Veuillez confirmer si vous souhaitez réinitialiser les chaînes de message','There are %d custom messages translations in this form (see %s panel)
                                that are not translatable because they are not put in {curly braces}. <br>
                                If you want to use the english default message strings which are translated automatically by WordPress, 
                                then you can reset the custom translations here.'=>'Ce formulaire contient %d traductions de messages personnalisés (voir l’onglet %s)
qui ne peuvent pas être traduits car ils ne sont pas placés entre {accolades}. <br>
Si vous souhaitez utiliser les chaînes de message par défaut en anglais, qui sont traduites automatiquement par WordPress,
vous pouvez réinitialiser les traductions personnalisées ici.','Messages'=>'Messages','Multilang/Polylang'=>'Multilingue/Polylang','https://andreasmuench.de'=>'https://andreasmuench.de','Andreas Münch'=>'Andreas Münch','Enables translation and use of the same forms in different languages of Contact Form 7 forms with Polylang'=>'Permet la traduction et l’utilisation des mêmes formulaires dans différentes langues pour les formulaires Contact Form 7 avec Polylang','Multilingual Contact Form 7 with Polylang'=>'Multilingual Contact Form 7 with Polylang']];