<?php
/**
 * ModuleRegistry — Auto-discovers and boots project Modules.
 *
 * Scans the Composer classmap for classes under HD\Modules\ namespace
 * that implement ModuleInterface. Active modules are instantiated and booted.
 *
 * Discovery results are cached as a transient for performance.
 * Run `ModuleRegistry::invalidateCache()` after adding/removing modules.
 *
 * @package HD\Core
 */

namespace HD\Core;

use HD\Contracts\HasAdminContext;
use HD\Contracts\HasDatabaseSchema;
use HD\Contracts\HasMigrations;
use HD\Contracts\ModuleInterface;

defined( 'ABSPATH' ) || exit;

final class ModuleRegistry {
	private const CACHE_KEY     = 'hd_module_map';
	private const CACHE_VERSION = '1';

	/** @var array<string, class-string<ModuleInterface>> slug => FQCN */
	private array $modules = [];

	/** @var array<string, ModuleInterface> slug => instance */
	private array $instances = [];

	/** @var list<class-string> API controller classes collected during boot. */
	private array $pendingApiClasses = [];

	private static ?self $instance = null;

	private function __construct() {}

	// --------------------------------------------------

	public static function getInstance(): self {
		return self::$instance ??= new self();
	}

	// --------------------------------------------------

	/**
	 * Discover module classes from Composer classmap.
	 *
	 * Reads the autoload_classmap.php generated by `composer dump-autoload -o`.
	 * Filters classes under HD\Modules\ that implement ModuleInterface
	 * and are not abstract.
	 */
	public function discover(): self {
		$cached = get_transient( self::cacheKey() );
		if ( self::isValidCachedMap( $cached ) ) {
			/** @var array<string, class-string<ModuleInterface>> $cached */
			$this->modules = $cached;

			return $this;
		}

		$classMapFile = THEME_PATH . 'vendor/composer/autoload_classmap.php';
		$classMap     = is_file( $classMapFile ) ? (array) require $classMapFile : [];

		foreach ( $classMap as $class => $file ) {
			// Only scan HD\Modules\*\*Module classes — skip sub-classes
			// (e.g. FieldTypes\NavMenu) whose parents may not exist yet.
			if (
				! str_starts_with( $class, 'HD\\Modules\\' )
				|| ! str_ends_with( $class, 'Module' )
				|| ! class_exists( $class )
				|| ! is_subclass_of( $class, ModuleInterface::class )
				|| ( new \ReflectionClass( $class ) )->isAbstract()
			) {
				continue;
			}

			$this->modules[ $class::slug() ] = $class;
		}

		set_transient( self::cacheKey(), $this->modules, WEEK_IN_SECONDS );

		return $this;
	}

	// --------------------------------------------------

	/**
	 * Boot all discovered active modules.
	 *
	 * For each module: check isActive(), instantiate, call boot(),
	 * and optionally call adminBoot() if in admin context.
	 */
	public function boot(): void {
		$apiClasses = [];

		foreach ( $this->modules as $slug => $class ) {
			try {
				if ( ! $class::isActive() ) {
					continue;
				}

				$instance = new $class();
				$instance->boot();

				if ( is_admin() && $instance instanceof HasAdminContext ) {
					$instance->adminBoot();
				}

				// Collect API classes for batch registration.
				array_push( $apiClasses, ...$class::apiClasses() );

				$this->instances[ $slug ] = $instance;
			} catch ( \Throwable $e ) {
				wp_trigger_error(
					__METHOD__,
					"Module '{$slug}' boot failed: " . $e->getMessage(),
					E_USER_WARNING
				);
			}
		}

		// Register all collected API routes in a single named hook.
		if ( ! empty( $apiClasses ) ) {
			$this->pendingApiClasses = $apiClasses;
			add_action( 'rest_api_init', [ $this, 'registerApiRoutes' ] );
		}
	}

	/**
	 * Register REST API routes for all booted modules.
	 * Hooked to `rest_api_init` — named method for removability.
	 */
	public function registerApiRoutes(): void {
		foreach ( $this->pendingApiClasses as $apiClass ) {
			( new $apiClass() )->register_routes();
		}
	}

	// --------------------------------------------------

	/**
	 * Invalidate the cached module map.
	 * Call after adding/removing module files + `composer dump-autoload -o`.
	 */
	public static function invalidateCache(): void {
		delete_transient( self::cacheKey() );
	}

	// --------------------------------------------------

	/** @return array<string, ModuleInterface> */
	public function instances(): array {
		return $this->instances;
	}

	/**
	 * Collect database schemas from all discovered modules implementing HasDatabaseSchema.
	 *
	 * Iterates ALL discovered modules (including inactive) so tables exist
	 * before a module is enabled — no migration needed at activation time.
	 *
	 * @return array<string, string> ['table_name' => 'SQL columns/keys']
	 */
	public function collectSchemas(): array {
		$schemas = [];

		foreach ( $this->modules as $class ) {
			if ( is_subclass_of( $class, HasDatabaseSchema::class ) ) {
				/** @var class-string<HasDatabaseSchema> $class */
				foreach ( $class::databaseSchemas() as $table => $sql ) {
					$schemas[ $table ] = $sql;
				}
			}
		}

		return $schemas;
	}

	/**
	 * Collect versioned migrations from modules implementing HasMigrations.
	 *
	 * @return array<string, array<string, callable(): void>> slug => [version => callback]
	 */
	public function collectMigrations(): array {
		$result = [];

		foreach ( $this->modules as $slug => $class ) {
			if ( is_subclass_of( $class, HasMigrations::class ) ) {
				/** @var class-string<HasMigrations> $class */
				$migrations = $class::migrations();
				if ( $migrations ) {
					$result[ $slug ] = $migrations;
				}
			}
		}

		return $result;
	}

	private static function cacheKey(): string {
		$themeVersion = defined( 'THEME_VERSION' ) ? (string) THEME_VERSION : 'dev';

		return self::CACHE_KEY . '_' . md5( self::CACHE_VERSION . '|' . $themeVersion );
	}

	private static function isValidCachedMap( mixed $cached ): bool {
		if ( ! is_array( $cached ) || empty( $cached ) ) {
			return false;
		}

		foreach ( $cached as $class ) {
			if ( ! is_string( $class ) || ! class_exists( $class ) ) {
				return false;
			}
		}

		return true;
	}
}
