<?php
/**
 * Module auto-discovery and lifecycle management.
 *
 * Replaces the manual module registration in Plugin::getModuleClassMap(),
 * config.php module entries, and SettingsHandlerTrait::getSettingsAwareModules().
 *
 * Discovery: scans Composer's classmap for classes implementing ModuleInterface.
 * Boot: only boots modules enabled via GlobalSetting checkbox (or alwaysActive).
 * Lifecycle: auto-collects DB tables, cron hooks, and option keys from modules.
 *
 * @package HDAddons\Core
 */

namespace HDAddons\Core;

use HDAddons\Contracts\HasDatabaseSchema;
use HDAddons\Contracts\HasSettings;
use HDAddons\Contracts\ModuleInterface;
use HDAddons\Helper;
use HDAddons\Modules\GlobalSetting\GlobalSetting;

defined( 'ABSPATH' ) || exit;

final class ModuleRegistry {

	private const CACHE_KEY     = 'hda_module_map';
	private const CACHE_VERSION = '1';

	/** @var array<string, class-string<ModuleInterface>> slug → FQCN */
	private array $modules = [];

	/** @var array<string, ModuleInterface> slug → booted instance */
	private array $instances = [];

	private static ?self $instance = null;

	public static function getInstance(): self {
		return self::$instance ??= new self();
	}

	// ── Cached Discovery ─────────────────────────────

	/**
	 * Discover all module classes from static module map.
	 *
	 * Uses pre-generated module map (generated during composer dump-autoload)
	 * to eliminate runtime reflection and autoloading overhead.
	 *
	 * Falls back to runtime discovery if map doesn't exist.
	 */
	public function discover(): void {
		// Try static module map first (generated by ModuleMapGenerator)
		$mapFile = HDA_PATH . 'src/Core/module-map.php';
		if ( is_file( $mapFile ) ) {
			$map = require $mapFile;
			foreach ( $map as $slug => $data ) {
				$this->modules[ $slug ] = $data['class'];
			}

			return;
		}

		// Fallback to runtime discovery (legacy, slower)
		$this->discoverRuntime();
	}

	/**
	 * Runtime module discovery (legacy fallback)
	 *
	 * Only used if static module map doesn't exist.
	 * This method triggers autoloading for all module classes.
	 *
	 * @deprecated Use static module map instead
	 */
	private function discoverRuntime(): void {
		$cached = get_transient( self::cacheKey() );
		if ( self::isValidCachedMap( $cached ) ) {
			/** @var array<string, class-string<ModuleInterface>> $cached */
			$this->modules = $cached;

			return;
		}

		$classMapFile = HDA_PATH . 'vendor/composer/autoload_classmap.php';
		$classMap     = is_file( $classMapFile ) ? (array) require $classMapFile : [];

		foreach ( $classMap as $class => $file ) {
			if (
				! str_starts_with( $class, 'HDAddons\\Modules\\' )
				|| ! str_ends_with( $class, 'Module' )
				|| ! class_exists( $class )
				|| ! is_subclass_of( $class, ModuleInterface::class )
				|| ( new \ReflectionClass( $class ) )->isAbstract()
			) {
				continue;
			}

			$this->modules[ $class::slug() ] = $class;
		}

		set_transient( self::cacheKey(), $this->modules, WEEK_IN_SECONDS );
	}

	// ── Boot ────────────────────────────────────────

	/**
	 * Boot all enabled modules.
	 *
	 * alwaysActive modules are booted regardless of checkbox state.
	 * Other modules are only booted if enabled in GlobalSetting.
	 */
	public function bootEnabled(): void {
		$config  = Helper::getOption( GlobalSetting::OPTION_NAME, [] );
		$enabled = $config[ GlobalSetting::KEY_MODULES ] ?? [];

		foreach ( $this->modules as $slug => $class ) {
			if ( ! $class::alwaysActive() && empty( $enabled[ $slug ] ) ) {
				continue;
			}

			try {
				$instance = new $class();
				$instance->boot();
				$this->instances[ $slug ] = $instance;
			} catch ( \Throwable $e ) {
				error_log( "[HDA] Module '{$slug}' boot failed: " . $e->getMessage() );
			}
		}
	}

	// ── Metadata for Settings UI ────────────────────

	/**
	 * Get module config for toggle list and sidebar.
	 *
	 * Returns only non-alwaysActive modules (those with a visible toggle).
	 *
	 * @return array<string, array{title: string, description: string, group: string}>
	 */
	public function getConfig(): array {
		$config = [];

		foreach ( $this->modules as $slug => $class ) {
			if ( $class::alwaysActive() ) {
				continue;
			}

			$config[ $slug ] = [
				'title'       => $class::title(),
				'description' => $class::description(),
				'group'       => $class::group(),
			];
		}

		return $config;
	}

	// ── Lifecycle Helpers (auto-collect) ─────────────

	/**
	 * Collect database schemas from all discovered modules implementing HasDatabaseSchema.
	 *
	 * Iterates ALL discovered modules (including disabled) so tables exist
	 * before a module is enabled — no migration needed at activation time.
	 *
	 * @return array<string, string> ['table_name' => 'SQL columns/keys']
	 */
	public function collectSchemas(): array {
		$schemas = [];

		foreach ( $this->modules as $class ) {
			if ( is_subclass_of( $class, HasDatabaseSchema::class ) ) {
				/** @var class-string<HasDatabaseSchema> $class */
				foreach ( $class::databaseSchemas() as $table => $sql ) {
					$schemas[ $table ] = $sql;
				}
			}
		}

		return $schemas;
	}

	/**
	 * Get all cron hooks from all modules.
	 *
	 * @return string[]
	 */
	public function getAllCronHooks(): array {
		$hooks = [];

		foreach ( $this->modules as $class ) {
			foreach ( $class::cronHooks() as $hook ) {
				$hooks[] = $hook;
			}
		}

		return $hooks;
	}

	/**
	 * Get explicit cron schedules from all modules.
	 *
	 * @return array<string, string> hook => recurrence
	 */
	public function getAllCronSchedules(): array {
		$schedules = [];

		foreach ( $this->modules as $class ) {
			foreach ( $class::cronSchedules() as $hook => $recurrence ) {
				$schedules[ $hook ] = $recurrence;
			}
		}

		return $schedules;
	}

	/**
	 * Get option keys map: slug → option key list.
	 *
	 * Used for uninstall cleanup — delete all module options.
	 *
	 * @return array<string, string[]>
	 */
	public function getOptionMap(): array {
		$map = [];

		foreach ( $this->modules as $slug => $class ) {
			$keys = $class::optionKeys();
			if ( $keys ) {
				$map[ $slug ] = $keys;
			}
		}

		return $map;
	}

	// ── Settings Save ───────────────────────────────

	/**
	 * Process settings save for all HasSettings modules.
	 *
	 * Routes form data to each module by checking for its optionKey()
	 * in the submitted data. Each module receives ONLY its own data.
	 *
	 * Form inputs use: name="hda_{slug}[field]"
	 * PHP parses this into: $_POST['_data']['hda_{slug}']['field']
	 *
	 * @param array $data Sanitized form data from AJAX submit.
	 */
	public function processSettingsSave( array $data ): void {
		foreach ( $this->modules as $class ) {
			if ( ! is_subclass_of( $class, HasSettings::class ) ) {
				continue;
			}

			/** @var class-string<HasSettings&ModuleInterface> $class */
			$key = $class::optionKey();

			if ( isset( $data[ $key ] ) ) {
				$class::saveSettings( (array) $data[ $key ] );
			}
		}
	}

	// ── Cache ───────────────────────────────────────

	/** Invalidate the module discovery cache. */
	public static function invalidateCache(): void {
		delete_transient( self::cacheKey() );
	}

	private static function cacheKey(): string {
		return self::CACHE_KEY . '_' . md5( self::CACHE_VERSION . '|' . HDA_VERSION );
	}

	private static function isValidCachedMap( mixed $cached ): bool {
		if ( ! is_array( $cached ) || empty( $cached ) ) {
			return false;
		}

		foreach ( $cached as $class ) {
			if ( ! is_string( $class ) || ! class_exists( $class ) ) {
				return false;
			}
		}

		return true;
	}

	// ── Accessors ───────────────────────────────────

	/** @return array<string, class-string<ModuleInterface>> */
	public function all(): array {
		return $this->modules;
	}

	/** @return array<string, ModuleInterface> */
	public function instances(): array {
		return $this->instances;
	}
}
