<?php
/**
 * Static Module Map
 *
 * Auto-generated by ModuleMapGenerator
 * DO NOT EDIT MANUALLY
 *
 * Generated: 2026-05-31 05:52:00
 * Modules: 18
 */

defined( 'ABSPATH' ) || exit;

return [
    'aspect_ratio' => [
        'class' => HDAddons\Modules\AspectRatio\AspectRatioModule::class,
        'group' => 'performance',
        'alwaysActive' => false,
    ],
    'contact_link' => [
        'class' => HDAddons\Modules\ContactLink\ContactLinkModule::class,
        'group' => 'tools',
        'alwaysActive' => false,
    ],
    'cron_manager' => [
        'class' => HDAddons\Modules\CronManager\CronManagerModule::class,
        'group' => 'tools',
        'alwaysActive' => false,
    ],
    'custom_code' => [
        'class' => HDAddons\Modules\CustomCode\CustomCodeModule::class,
        'group' => 'tools',
        'alwaysActive' => false,
    ],
    'custom_sorting' => [
        'class' => HDAddons\Modules\CustomSorting\CustomSortingModule::class,
        'group' => 'tools',
        'alwaysActive' => false,
    ],
    'editor' => [
        'class' => HDAddons\Modules\Editor\EditorModule::class,
        'group' => 'tools',
        'alwaysActive' => false,
    ],
    'file' => [
        'class' => HDAddons\Modules\File\FileModule::class,
        'group' => 'performance',
        'alwaysActive' => false,
    ],
    'global_setting' => [
        'class' => HDAddons\Modules\GlobalSetting\GlobalSettingModule::class,
        'group' => 'general',
        'alwaysActive' => true,
    ],
    'image_converter' => [
        'class' => HDAddons\Modules\ImageConverter\ImageConverterModule::class,
        'group' => 'performance',
        'alwaysActive' => false,
    ],
    'login_security' => [
        'class' => HDAddons\Modules\LoginSecurity\LoginSecurityModule::class,
        'group' => 'security',
        'alwaysActive' => false,
    ],
    'logs' => [
        'class' => HDAddons\Modules\Logs\LogsModule::class,
        'group' => 'tools',
        'alwaysActive' => false,
    ],
    'maintenance' => [
        'class' => HDAddons\Modules\Maintenance\MaintenanceModule::class,
        'group' => 'tools',
        'alwaysActive' => false,
    ],
    'optimize' => [
        'class' => HDAddons\Modules\Optimize\OptimizeModule::class,
        'group' => 'performance',
        'alwaysActive' => false,
    ],
    'post_type_archive' => [
        'class' => HDAddons\Modules\PostTypeArchive\PostTypeArchiveModule::class,
        'group' => 'tools',
        'alwaysActive' => false,
    ],
    'recaptcha' => [
        'class' => HDAddons\Modules\Recaptcha\RecaptchaModule::class,
        'group' => 'security',
        'alwaysActive' => false,
    ],
    'redirect' => [
        'class' => HDAddons\Modules\Redirect\RedirectModule::class,
        'group' => 'tools',
        'alwaysActive' => false,
    ],
    'security' => [
        'class' => HDAddons\Modules\Security\SecurityModule::class,
        'group' => 'security',
        'alwaysActive' => false,
    ],
    'social_link' => [
        'class' => HDAddons\Modules\SocialLink\SocialLinkModule::class,
        'group' => 'tools',
        'alwaysActive' => false,
    ],
];
