<?php
/**
 * Import Handler — orchestrates translation file import.
 *
 * Handles file upload, format detection, validation, and delegates
 * to the appropriate Importer strategy for processing.
 *
 * @package HD\Modules\PLL\ImportExport
 */

namespace HD\Modules\PLL\ImportExport;

use HD\Modules\PLL\ImportExport\Format\CsvImporter;
use HD\Modules\PLL\ImportExport\Format\PoImporter;
use HD\Modules\PLL\ImportExport\Format\XliffImporter;

defined( 'ABSPATH' ) || exit;

final class ImportHandler {
	private const STRING_IMPORT_CHUNK_SIZE = 200;

	/**
	 * Process an uploaded translation file.
	 *
	 * @param array  $file       $_FILES entry (tmp_name, type, size, etc.).
	 * @return array{imported: int, type: string, warnings: string[]}|\WP_Error
	 */
	public static function handle( array $file ): array|\WP_Error {
		if ( ! function_exists( 'PLL' ) ) {
			return new \WP_Error( 'pll_import_unavailable', __( 'Polylang is not available.', 'hd' ) );
		}

		// ── Upload ──
		$factory = new FileFormatFactory();

		// Temporarily allow translation file MIME types.
		$allowMimes = static fn( array $mimes ): array => array_merge( $mimes, $factory->getAllowedMimeTypes() );
		add_filter( 'upload_mimes', $allowMimes ); // phpcs:ignore WordPressVIPMinimum.Hooks.RestrictedHooks.upload_mimes

		$upload = wp_handle_upload( $file, [ 'test_form' => false ] );

		remove_filter( 'upload_mimes', $allowMimes );

		if ( isset( $upload['error'] ) ) {
			return new \WP_Error( 'pll_import_upload_failed', $upload['error'] );
		}

		if ( empty( $upload['type'] ) || empty( $upload['file'] ) ) {
			return new \WP_Error( 'pll_import_upload_failed', __( 'Upload failed.', 'hd' ) );
		}

		// ── Detect format & parse ──
		$importer = $factory->createImporterFromMime( $upload['type'] );

		// Fallback: try extension-based detection for CSV (MIME might be text/plain).
		if ( \is_wp_error( $importer ) ) {
			$ext      = pathinfo( $upload['file'], PATHINFO_EXTENSION );
			$importer = match ( strtolower( $ext ) ) {
				'csv'           => new CsvImporter(),
				'po'            => new PoImporter(),
				'xliff', 'xlf'  => new XliffImporter(),
				default         => $importer,
			};
		}

		if ( \is_wp_error( $importer ) ) {
			wp_delete_file( $upload['file'] );

			return $importer;
		}

		$parseResult = $importer->importFromFile( $upload['file'] );
		wp_delete_file( $upload['file'] );

		if ( \is_wp_error( $parseResult ) ) {
			return $parseResult;
		}

		// ── Validate metadata ──
		$validationError = self::validate( $importer );
		if ( \is_wp_error( $validationError ) ) {
			return $validationError;
		}

		// ── Resolve target language ──
		$targetLocale = $importer->getTargetLanguage();
		if ( false === $targetLocale ) {
			return new \WP_Error( 'pll_import_no_target', __( 'Error: No target language found in the file.', 'hd' ) );
		}

		$targetLang = \PLL()->model->get_language( $targetLocale );
		if ( ! $targetLang ) {
			return new \WP_Error(
				'pll_import_invalid_target',
				__( "Error: The target language in the file doesn't exist on this site.", 'hd' )
			);
		}

		// ── Process entries ──
		return self::processEntries( $importer, $targetLang );
	}

	/**
	 * Validate importer metadata (site reference, generator).
	 *
	 * @param Contracts\ImporterInterface $importer The importer instance.
	 *
	 * @return bool|\WP_Error
	 */
	private static function validate( Contracts\ImporterInterface $importer ): bool|\WP_Error {
		// Validate site reference.
		$siteRef = $importer->getSiteReference();
		if ( false !== $siteRef && $siteRef !== get_site_url() ) {
			return new \WP_Error(
				'pll_import_site_mismatch',
				sprintf(
					/* translators: %1$s: file site URL, %2$s: current site URL */
					__( 'Error: Site mismatch. File: %1$s, Current: %2$s.', 'hd' ),
					$siteRef,
					get_site_url()
				)
			);
		}

		// Validate generator.
		$generator = $importer->getGeneratorName();
		if ( '' !== $generator && FileFormatFactory::APP_NAME !== $generator ) {
			return new \WP_Error(
				'pll_import_wrong_generator',
				sprintf(
					/* translators: %s: generator name */
					__( 'Error: This file was not generated by %s.', 'hd' ),
					FileFormatFactory::APP_NAME
				)
			);
		}

		return true;
	}

	/**
	 * Process translation entries from the importer.
	 *
	 * @param Contracts\ImporterInterface $importer   The importer instance.
	 * @param \PLL_Language               $targetLang Target language object.
	 *
	 * @return array{imported: int, type: string, warnings: string[]}
	 */
	private static function processEntries( Contracts\ImporterInterface $importer, \PLL_Language $targetLang ): array {
		$warnings    = [];
		$stringBatch = [];
		$imported    = 0;

		$entry = $importer->getNextEntry();

		while ( ! empty( $entry ) ) {
			$entryType = $entry['type'] ?? '';

			if ( 'strings-translations' === $entryType ) {
				$stringBatch[] = $entry['data'];

				if ( count( $stringBatch ) >= self::STRING_IMPORT_CHUNK_SIZE ) {
					$imported   += self::importStrings( $stringBatch, $targetLang );
					$stringBatch = [];
				}
			}

			$entry = $importer->getNextEntry();
		}

		// ── Strings ──
		if ( ! empty( $stringBatch ) ) {
			$imported += self::importStrings( $stringBatch, $targetLang );
		}

		return [
			'imported' => $imported,
			'type'     => 'strings',
			'warnings' => $warnings,
		];
	}

	/**
	 * Import string translations into PLL MO.
	 *
	 * Handles 3 data formats (batched):
	 * - PO object (from PoImporter)
	 * - XLIFF array of {source, target} (from XliffImporter)
	 * - CSV array of {string, translations} (from CsvImporter)
	 *
	 * @param array         $dataBatch  Array of translation data batches.
	 * @param \PLL_Language $targetLang Target language.
	 *
	 * @return int Number of strings imported.
	 */
	private static function importStrings( array $dataBatch, \PLL_Language $targetLang ): int {
		if ( ! class_exists( 'PLL_MO' ) || empty( $dataBatch ) ) {
			return 0;
		}

		$mo = new \PLL_MO();
		$mo->import_from_db( $targetLang );
		$count = 0;

		foreach ( $dataBatch as $data ) {
			// PO object (from PoImporter) — batch of Translation_Entry.
			if ( $data instanceof \Translations ) {
				foreach ( $data->entries as $entry ) {
					/** @var \Translation_Entry $entry */
					$translation = $entry->translations[0] ?? '';

					if ( '' !== $translation && '' !== $entry->singular ) {
						$mo->add_entry( $mo->make_entry( $entry->singular, wp_kses_post( $translation ) ) );
						++$count;
					}
				}

				continue;
			}

			if ( ! is_array( $data ) ) {
				continue;
			}

			// CSV entry: {string, translations: {locale => value}}.
			if ( isset( $data['string'], $data['translations'] ) ) {
				$translation = $data['translations'][ $targetLang->locale ] ?? '';

				if ( '' !== $translation && '' !== $data['string'] ) {
					$mo->add_entry( $mo->make_entry( $data['string'], wp_kses_post( $translation ) ) );
					++$count;
				}

				continue;
			}

			// XLIFF map: field_id => {source, target}.
			foreach ( $data as $field ) {
				if ( ! is_array( $field ) ) {
					continue;
				}

				$source = $field['source'] ?? '';
				$target = $field['target'] ?? '';

				if ( '' !== $source && '' !== $target ) {
					$mo->add_entry( $mo->make_entry( $source, wp_kses_post( $target ) ) );
					++$count;
				}
			}
		}

		if ( $count > 0 ) {
			$mo->export_to_db( $targetLang );
		}

		return $count;
	}
}
